#!/bin/bash


param_check () 
{
	if [ -z "$3" ] 
	then
		echo "Not enough arguments given"
		exit
	fi
}



if [ "$1" = "install" ]
then
	if [ "$2" = "module" ]
	then
		#TODO: add module .c files to makefile and compile module files
		echo "TODO"
	elif [ "$2" = "project" ]
	then
		#TODO: compile all .c files
		echo "TODO"
	else
		echo "Unkown install argument: ${2}"
	fi
elif [ "$1" = "remove" ]
then
	if [ "$2" = "module" ]
	then
		param_check
		rm -r modules/$3
		#TODO: remove the .c files from the makefile
	elif [ "$2" = "project" ]
	then
		rm -r modules states
		rm .Makefile
		#TODO: remove states folder
	else
		echo "Unkown remove argument: ${2}"
	fi
elif [ "$1" = "create" ]
then
	if [ "$2" = "module" ]
	then
		param_check
		mkdir modules/$3
		echo -e "#ifndef ${3^^}_MOD_H\n#define ${3^^}_MOD_H\n\n\n\n#endif" > modules/$3/$3.h 
		#-e makes echo interpret \n as a newline character, otherwise it would just print it into the file
		#^^ makes the string before that fully uppercase
	elif [ "$2" = "project" ]
	then
		param_check
		mkdir modules
		mkdir states
		#the - after << make it ignore leading tabs
		cat > .Makefile <<- EOF
		VERSION = -std=c99
		LIBS = 
		MODE = -g
		OPTIMIZATIONS = -O0
		ERRORFLAGS = -Wall -Wuninitialized -Werror=implicit-function-declaration -Wextra -Wno-unused-parameter -Wno-incompatible-pointer-types -Werror=int-conversion
		LFLAGS = -o
		CFLAGS = \$(ERRORFLAGS) \$(VERSION) \$(OPTIMIZATIONS) -c \$(MODE)
		OBJFILES = 


		com: \$(OBJFILES)
			gcc \$(LFLAGS) ${3} \$(OBJFILES) \$(LIBS)

		run:
			./${3}
		EOF
	else
		echo "Unkown create argument: ${2}"
	fi
else
	echo "Unkown command: ${1}"
fi